name: neodohae_nextjs CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: 076831690411.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: neodohae_nextjs

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout neodohae_nextjs repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm run test:ci

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env.production
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env.production
        echo "KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }}" >> .env.production
        echo "KAKAO_CLIENT_SECRET=${{ secrets.KAKAO_CLIENT_SECRET }}" >> .env.production
        echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env.production
        echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env.production
        echo "SSO_GITHUB_CLIENT_ID=${{ secrets.SSO_GITHUB_CLIENT_ID }}" >> .env.production
        echo "SSO_GITHUB_CLIENT_SECRET=${{ secrets.SSO_GITHUB_CLIENT_SECRET }}" >> .env.production
        echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env.production
        echo "NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}" >> .env.production
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.production
        echo "API_SERVER_URI=${{ secrets.API_SERVER_URI }}" >> .env.production
        echo "PORT=${{ secrets.PORT }}" >> .env.production
        echo "VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}" >> .env.production
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Checkout neodohae_helm_charts repository
      uses: actions/checkout@v2
      with:
        repository: peterhyun1234/neodohae_helm_charts
        persist-credentials: false
        fetch-depth: 0

    - name: Install yq
      run: |
        sudo wget -O /usr/bin/yq https://github.com/mikefarah/yq/releases/download/v4.6.1/yq_linux_amd64
        sudo chmod +x /usr/bin/yq

    - name: Update values.yaml and push to repository
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        yq e ".image.tag = env(IMAGE_TAG)" -i neodohae_nextjs/values.yaml
        cat neodohae_nextjs/values.yaml

        git config --global user.name 'peter jeon'
        git config --global user.email 'peterhyun1234@gmail.com'

        git add .
        git commit -m "feat: update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
        git push https://${{ secrets.PAT }}@github.com/peterhyun1234/neodohae_helm_charts.git
